### ISSUE TITLE
Implement kcidb.oo module tests

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#207]
After reimplementing the OO module we don't have tests for it anymore. Implement unit tests for the kcidb.oo module.

**Comment by mrbazzan** [comment]
@spbnick 
What am I testing for? I don't really understand the underlying concept of what the oo module does

**Comment by spbnick** [comment]
The OO module provides an object-oriented interface to a database. The main entry point is the `Client` class. You create a client, giving it a data source. Then you can query objects from the database using the `query()` function, supplying it with the pattern set matching the objects you want retrieved.

Here are some examples: https://github.com/kernelci/kcidb/blob/12f9be53cadbe1ac81ef1eced7da6c07ae23c3a0/kcidb/__init__.py#L370-L424

With that in mind, most basic tests would be loading some known data into a database (e.g. an SQLite database), and then checking that queries return correct objects. Would be good to think of and test some corner cases.

**Comment by mrbazzan** [comment]
Okay. Thanks.
Could you give me a quick overview of (Pattern & pattern sets) and Relation in kcidb.orm

**Comment by spbnick** [comment]
A Pattern object specifies particular objects in the database. It could be as simple as "a build with ID `redhat:23422121`", or it could be "all builds of checkout `kernelci:198723498712`", or even "all tests of all builds of all checkouts of revisions with commit hashes `1235abbd34`, `ad8787faa`, and `22309098a3`, all without patchset hashes". It could also go in the other direction of ownership, and could say "the checkout of the build of the test with ID `arm:12987987aad`".

Patterns have a text representation, which is somewhat more powerful than that, where you could say "all objects owned by a revision with commit hash 89879aff23e and no patchset hash, including the revision itself". This would look something like `>revision[89879aff23e, ""]#>*#`. That would be parsed into multiple Pattern objects, one for each type of database objects. There would be no single object representing that expression, and we would need to address that eventually, but for now it's OK this way.

For reference, the examples of Pattern objects in the first paragraph could be rendered in text like this:

* `>build[redhat:23422121]#` - "a build with ID `redhat:23422121`";
* `>checkout[kernelci:198723498712]>build#` - "all builds of checkout `kernelci:198723498712`";
* `>revision[1235abbd34,""; ad8787faa, ""; 22309098a3, ""]>checkout>build>test#` - "all tests of all builds of all checkouts of revisions with commit hashes `1235abbd34`, `ad8787faa`, and `22309098a3`, all without patchset hashes";
* `>test[arm:12987987aad]<build<checkout#` - "the checkout of the build of the test with ID `arm:12987987aad`".

Finally, the `>revision[89879aff23e, ""]#>*#` pattern from the second paragraph could be rendered as text like the below set of patterns after parsing, and then formatting as text again:
* `>revision[89879aff23e, ""]#`
* `>revision[89879aff23e, ""]>checkout#`
* `>revision[89879aff23e, ""]>checkout>build#`
* `>revision[89879aff23e, ""]>checkout>build>test#`

This asymmetry is what I refer to as something we might need to address eventually.

Patterns are used to specify the particular objects to fetch from a data source (a `kcidb.orm.Source` subtype, e.g. `kcidb.db.Client`), in the internal object-oriented representation, using the `oo_query()` method.

**Comment by spbnick** [comment]
`Relation` is an object recording parent-child relation between two object types in a database, as well as which database fields are used to link them. It's used as part of the object-oriented database schema (`kcidb.orm.Schema`) class to record the relationship graph.

If you run this command (having installed the `graphviz` package):
```bash
python3 -c 'import kcidb.orm; print(kcidb.orm.SCHEMA.format_dot())' | dot -Tx11
```
You will see the current schema's relationship graph, which is recorded in part using these objects. The whole schema, including the relationships is stored in `kcidb.orm.SCHEMA`. Check out how it's generated, if you wanna know more.

**Comment by spbnick** [comment]
Here's a [sample](https://github.com/kernelci/kcidb/files/7587868/sample.tar.gz) of data KCIDB has received from submitting CI systems since some time in the morning.

You can create an empty SQLite database like this:

    kcidb-db-init -d sqlite:sample.sqlite3

And then load the sample into it like this (will take a while):

    tar xOf sample.tar.gz | kcidb-db-load -d sqlite:sample.sqlite3

You can view the JSON files inside the submission sample by just unpacking it somewhere, or like this:

    tar xOf sample.tar.gz | less -S

You can find the IDs of the objects you loaded there.

You can query the ORM representation of the objects with patterns using `kcidb-oo-query`. E.g. this will give you all revisions:

    kcidb-oo-query -d sqlite:sample.sqlite3 '>revision#'

This will give you one of them:

    kcidb-oo-query -d sqlite:sample.sqlite3 '>revision[e0e05de128590faae59001713264c68863d73209,""]#'

And this will give you the revision and all its children:

    kcidb-oo-query -d sqlite:sample.sqlite3 '>revision[e0e05de128590faae59001713264c68863d73209,""]#>*#'

This will give you all the tests:

    kcidb-oo-query -d sqlite:sample.sqlite3 '>test#'

This will give you one of them:

    kcidb-oo-query -d sqlite:sample.sqlite3 '>test[arm:LTP:35482480]#'

And this will give you the test and all its parents:

    kcidb-oo-query -d sqlite:sample.sqlite3 '>test[arm:LTP:35482480]#<*#'

Finally, this will give you the test's revision, and all **its** children, the test among them:

    kcidb-oo-query -d sqlite:sample.sqlite3 '>test[arm:LTP:35482480]<*$>*#'

Play around with this to get the feel for the patterns.

**Comment by mrbazzan** [comment]
> `Relation` is an object recording parent-child relationship between two object types in a database, as well as which database fields are used to link them. It's used as part of the object-oriented database schema (`kcidb.orm.Schema`) class to record the relationship graph.
> 
> If you run this command (having installed the `graphviz` package):
> 
> ```shell
> python3 -c 'import kcidb.orm; print(kcidb.orm.SCHEMA.format_dot())' | dot -Tx11
> ```
> 
> You will see the current schema's relationship graph, which is recorded in part using these objects. The whole schema, including the relationships is stored in `kcidb.orm.SCHEMA`. Check out how it's generated, if you wanna know more.

I understood `Relation` a bit, I just wanted to be certain of the whole picture.

Thanks, I have an idea of how the Pattern class works now. The detailed explanation you gave really helped.

**Comment by mrbazzan** [comment]
> Here's a [sample](https://github.com/kernelci/kcidb/files/7587868/sample.tar.gz) of data KCIDB has received from submitting CI systems since some time in the morning.
> 
> You can create an empty SQLite database like this:
> 
> ```
> kcidb-db-init -d sqlite:sample.sqlite3
> ```
> 
> And then load the sample into it like this (will take a while):
> 
> ```
> tar xOf sample.tar.gz | kcidb-db-load -d sqlite:sample.sqlite3
> ```
> 
> You can view the JSON files inside the submission sample by just unpacking it somewhere, or like this:
> 
> ```
> tar xOf sample.tar.gz | less -S
> ```
> 
> You can find the IDs of the objects you loaded there.
> 
> You can query the ORM representation of the objects with patterns using `kcidb-oo-query`. E.g. this will give you all revisions:
> 
> ```
> kcidb-oo-query -d sqlite:sample.sqlite3 '>revision#'
> ```
> 
> This will give you one of them:
> 
> ```
> kcidb-oo-query -d sqlite:sample.sqlite3 '>revision[e0e05de128590faae59001713264c68863d73209,""]#'
> ```
> 
> And this will give you the revision and all its children:
> 
> ```
> kcidb-oo-query -d sqlite:sample.sqlite3 '>revision[e0e05de128590faae59001713264c68863d73209,""]#>*#'
> ```
> 
> This will give you all the tests:
> 
> ```
> kcidb-oo-query -d sqlite:sample.sqlite3 '>test#'
> ```
> 
> This will give you one of them:
> 
> ```
> kcidb-oo-query -d sqlite:sample.sqlite3 '>test[arm:LTP:35482480]#'
> ```
> 
> And this will give you the test and all its parents:
> 
> ```
> kcidb-oo-query -d sqlite:sample.sqlite3 '>test[arm:LTP:35482480]#<*#'
> ```
> 
> Finally, this will give you the test's revision, and all **its** children, the test among them:
> 
> ```
> kcidb-oo-query -d sqlite:sample.sqlite3 '>test[arm:LTP:35482480]<*$>*#'
> ```
> 
> Play around with this to get the feel for the patterns.

:) 
Thanks for the sample. I will play around with it and hopefully, get a better insight.

**Comment by mrbazzan** [comment]
What do you think about providing all this information in a file for people interested in contributing? It'll really help.

**Comment by spbnick** [comment]
> What do you think about providing all this information in a file for people interested in contributing? It'll really help.

Yeah I was thinking about that too. I think either the `doc/developer_guide.md`, comments in `kcidb/orm/__init__.py`, or the corresponding docstrings would be a good place, depending on the shape. Would you be interested in doing that?

**Comment by mrbazzan** [comment]
The `doc/developer_guide.md` seems like the way to go. `kcidb/orm/__init__.py` already has a lot of information already.

Yes, I would like to do it.

**Comment by mrbazzan** [comment]
@spbnick 
Congrats on v9.

Kindly help review the test.

**Comment by spbnick** [comment]
> @spbnick Congrats on v9.

Thanks :grin:

> Kindly help review the test.

Done!

**Comment by spbnick** [comment]
Yeah, I was just thinking about it, but maybe we could open a new one instead, for expanding the tests, and describe what needs to be done, because, technically, we have **some** tests already :)
