### ISSUE TITLE
Add tests for kcidb-ingest

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#242]
Add tests for the kcidb-ingest tool. Use `test_notify_main()` in `test_kcidb.py` as a reference.

**Comment by Mbaoma** [comment]
Hi, i'd like to tinker around with this for a few days and see if I can do anything reasonable. cool? @spbnick

**Comment by spbnick** [comment]
Absolutely! The issue as is is more of a reminder, and is really bare-bones, sorry, didn't have the time to fill it in yet, for this Outreachy round

You can start with checking out the `kcidb` package, then installing it for local development, e.g. with `pip3 install --user -e '.[dev]'` (see more instruction in docs), and then playing with the installed `kcidb-ingest` tool.

E.g. you can take the attached [test.json.gz](https://github.com/kernelci/kcidb/files/10901810/test.json.gz), unpack it, and feed it to the tool: `kcidb-ingest < test.json`. It should output a bunch of email messages one after another.

The test should try to feed it various options and inputs and verify that it produces appropriate outputs. You can try to figure out which those would be, but if not, I can post a description of what could be done tomorrow.

Have fun!

**Comment by Mbaoma** [comment]
Hi @spbnick I try to setup kcidb on my mac, but keep getting a python wheel error.
are there specific steps to set this up on a mac?

**Comment by Mbaoma** [comment]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/49791498/224381403-19235bac-a1c9-424e-b076-3a218c57ad74.png">

**Comment by spbnick** [comment]
Ah, it could be a big pain in the rear to get this working on a Mac, although that's possible. You'd need to install a bunch of packages from Brew, and a toolchain or something like that, and I can't remember exactly which ones you need and how to install them. I would recommend you install a Linux distro (e.g. Ubuntu) in a VM, and work from there. If you'd prefer not to do that, you'll need to wait for me to find a couple hours to help you with this, next week.

**Comment by spbnick** [comment]
Good luck!

**Comment by spbnick** [comment]
If you can't find people to help you, try asking ChatGPT :robot:

**Comment by Mbaoma** [comment]
sure thing!

**Comment by spbnick** [comment]
Removing @Mbaoma from the assignees, as Outreachy's initial contribution period is now over.
