### ISSUE TITLE
Expand kcidb.oo module tests

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#293]
We have [just merged](https://github.com/kernelci/kcidb/pull/247) the first basic tests of the `kcidb.oo` module. It would be good to add more tests.

As a start, we could use the following setup:

- [x] Load the following data for a revision into an SQLite database:
  - [x] Two valid checkouts, and one invalid checkout, using the same commit hash, and with repositories "https://repo_valid", "https://repo_valid", and "https://repo_invalid", and branches "branch_valid1", "branch_valid2", and "branch_invalid" respectively.
  - [x] Two valid, and one invalid build for each valid checkout, using architectures "valid1", "valid2", and "invalid" respectively
  - [x] Two passed, and one failed tests for each valid build, using paths "pass1", "pass2", and "fail" respectively

Do the following when accessing the database through the OO client:

- [ ] Check that database objects can be traversed using the OO representation:
  - [x] Check that the revision's links can be successfully traversed, including:
    - [x] The `repo_branch_checkouts` property has all checkouts loaded into the database, indexed by their repositories and branches
    - [x] The `architecture_valid_builds` property has all six builds, indexed by their architectures and valid status
    - [x] The `builds` property has all six loaded builds
    - [x] The `tests` property has all twelve loaded tests
    - [x] The `tests_root` property returns the root test node (`Node` instance)
  - [x] Check that links of a valid checkout can be successfully traversed, including:
    - [x] The `revision` property points to the correct revision object
    - [x] The `builds` property has all three of the loaded builds
    - [x] The `tests` property has all six loaded tests
    - [x] The `tests_root` property returns the root test node (`Node` instance)
  - [x] Check that links of a valid build can be successfully traversed, including:
    - [x] The `checkout` property points to the correct checkout object
    - [x] The `tests` property has all three loaded tests
    - [x] The `tests_root` property returns the root test node (`Node` instance)
  - [x] Check that links of a test can be successfully traversed, including:
    - [x] The `build` property points to the correct build object
  - [x] Check that links of the revision's root test node (`Node` instance from revision's `tests_root`) can be successfully traversed, including:
    - [x] The `parent` property points to the revision object
    - [x] The `tests` property contains an empty array
    - [x] The `nodes` property contains three sub-nodes, with paths "pass1", "pass2", and "fail", and each of those nodes:
      - [x] Has `parent` property point to the containing node
      - [x] Has four tests with the same corresponding `path` in `tests` property
      - [x] Has `nodes` property containing empty array

**Comment by spbnick** [comment]
@mrbazzan, if you're interested in expanding OO tests, this should get you started :smile:

**Comment by mrbazzan** [comment]
Wow!! This is so comprehensive.
I'll get right on it.

**Comment by mrbazzan** [comment]
Hi @spbnick, 
Could you tell me a little bit about kcidb.oo.Node?

**Comment by spbnick** [comment]
Sure, @mrbazzan, and sorry for my delayed answer I've been trying hard to deal with our rising BigQuery costs in Google Cloud, and the solution is still out of my reach, so expect more delays.

The name `Node` is unfortunate and is only there, because the name "test" was taken by the database objects, which should instead be called something like "test run". I think I might have gone over that earlier :thinking: Ideally, "test" and `Test` should be called "test_run" and `TestRun`, or just "run" and `Run` and `Node` - `Test`.

I.e. basically `Node` is a test, or a subtest of one, that could be executed. An execution is represented by `Test`. The tree of "nodes" is the tree of tests. You can browse that tree, and see each execution of the selected node and nodes below e.g. here: https://kcidb.kernelci.org/d/revision/revision?orgId=1&var-git_commit_hash=088fb7eff349423e3d8bb4ce7c63bbb302b3d41a&var-patchset_hash=&var-dataset=kcidb_01&var-origin=All&var-build_architecture=All&var-build_config_name=All&var-test_path=

Here you can see that the "Root" node is currently selected and its summarized status (the overall status of all tests) is "FAIL":

![image](https://user-images.githubusercontent.com/549246/165567938-d3c123f4-2eb2-45f9-a1d8-59a2c316abfc.png)

Here you can see the nodes directly below it, that is test suites "boot", "open-posix", and "ltp". You can click on any of them to see the nodes below.

![image](https://user-images.githubusercontent.com/549246/165568349-25fd0d09-72f9-44f8-85e3-2c6b36c6b67a.png)

And here you can see all tests for the root node and nodes below it (that is **all** tests):

![image](https://user-images.githubusercontent.com/549246/165568665-ded35fa1-30d2-412a-8001-5128af222784.png)

Play with the UI to get a feel for it.

In KCIDB Python code the `Node` objects are needed to be able to summarize test results for a particular test/revision/build.

Does this make sense?

**Comment by mrbazzan** [comment]
> Does this make sense?

Yes, it does. Thanks

> In KCIDB Python code the `Node` objects are needed to be able to summarize test results for a particular test/revision/build.

`Node` objects can be used to summarize test results for a test? It should only work for a build/revision/checkout.

**Comment by spbnick** [comment]
> `Node` objects can be used to summarize test results for a test? It should only work for a build/revision/checkout, right?

Yeah, that was supposed to be `revision/checkout/build`, I think :see_no_evil:

**Comment by mrbazzan** [comment]
Hi @spbnick,
We should be more or less done with this issue(took quite some time :sweat_smile:). I have a couple of questions though:
1) Are there more OO related tests?

2) `postgresql` db was introduced to help with [this issue](https://github.com/kernelci/kcidb/issues/294), right? I don't really understand the underlying problem, and how `postgresql` helps to solve/reduce the problem.

3) What other aspects of KCIDB do you need work done on?

**Comment by spbnick** [comment]
> We should be more or less done with this issue(took quite some time :sweat_smile:).

Great! Thank you :relaxed: Let's close it, then.

> Are there more OO related tests?

I think this should be good enough for now. We shouldn't add too many tests for something that is likely going to change considerably some time soon.

> postgresql db was introduced to help with https://github.com/kernelci/kcidb/issues/294, right?

Not exactly. Rather we failed to implement #294 due to conflict between our deduplication protocol and BigQuery implementation, and fell back to a plan involving PostgreSQL.

> I don't really understand the underlying problem, and how postgresql helps to solve/reduce the problem.

#294 was aimed at reducing BigQuery costs, which could be staggering because of the table size and the amount of queries we need to do for generating result notifications for developers. So, we decided to instead load data into both BigQuery and a PostgreSQL instance, and move notification generation to the latter. PostgreSQL has better support for "interactive queries", but less support for huge datasets (we don't have those yet, but we might). More importantly it seems to be much cheaper.

**Comment by spbnick** [comment]
> Okay. Where was that implemented?

Still implementing it :smiley:
