### ISSUE TITLE
Docker image failing to build due to error with `jq` install

### ISSUE THREAD

**Issue by gctucker** [kernelci/kcidb#317]
An error started appearing while building the KCIDB Docker image used with the new KernelCI pipeline:

```
Successfully built kcidb kcidb-io psycopg2
Failed to build jq
ERROR: Could not build wheels for jq, which is required to install pyproject.toml-based projects
WARNING: You are using pip version 22.0.3; however, version 22.2.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
ERROR: Service 'kcidb' failed to build: The command '/bin/sh -c pip install git+https://github.com/kernelci/kcidb.git' returned a non-zero code: 1
```

I believe that's not specific to the Docker image but rather an issue with `jq` when installing the KCIDB requirements.

**Comment by gctucker** [comment]
In principle this can be reproduced using the following command in `kernelci-pipeline`:
```
docker-compose build --no-cache kcidb
```
However I saw that in the staging logs but it worked when I tried again by hand, so maybe it was only a temporary glitch with a package that failed to get downloaded or something.  I'll keep an eye on it.

**Comment by spbnick** [comment]
Yeah, couldn't reproduce this locally either, everything worked :man_shrugging:

**Comment by gctucker** [comment]
OK closing now, will re-open if it comes back. Thank you
