### ISSUE TITLE
Update documentation to instruct using latest kcidb

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#353]
Releases are going away in favor of continuous integration and deployment, so update the documentation to direct users to downloading the latest `main` branch.

This is done, when all files in the `doc` directory stop directing readers to download the latest or specific release, and instead tell them to download/install the latest `main` branch.

**Comment by octonawish-akcodes** [comment]
Can I work on this one sir

**Comment by spbnick** [comment]
Hi Abhishek! Sure, let's start with this one.
