### ISSUE TITLE
Support deploying with specified value of PYTHONOPTIMIZE

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#371]
We're still struggling with timeouts in notification-generation Cloud Function (#360), and while that needs to be properly investigated/optimized, we could improve the matter by disabling assertions in our Python code.

Add support for specifying a value for PYTHONOPTIMIZE to be added to the environment, via a command-line option to the [`cloud`](https://github.com/kernelci/kcidb/blob/main/cloud) tool. Something like `--optimize=<integer>`, which would default to zero (no optimization).

Take the implementation of `--log-level` option as a reference.

**Comment by octonawish-akcodes** [comment]
I want to work on this.

**Comment by spbnick** [comment]
Sure! Go ahead. This involves modifying the Bash code in the `cloud` tool. Have fun!

**Comment by spbnick** [comment]
For testing the tool, you could register for a new Google Cloud account, which would be free for half a year, IIRC. Then you would be able to use the `cloud` tool to deploy KCIDB there.
