### ISSUE TITLE
Switch to new BigQuery dataset access API

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#378]
We started receiving the following warning from Google Cloud APIs:
> /home/nkondras/projects/github.com/kernelci/kcidb/kcidb/db/bigquery/v04_00.py:71: PendingDeprecationWarning: Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
> self.dataset_ref = self.client.dataset(dataset_name)

Update the code to silence the warning and prepare for the removal of the old API.

This will very likely require us to make the name of the Google Cloud project mandatory in "database specifications" in the `kcidb.db` package, and all the code using it. In that case, notify the package users of the impeding change (or ask @spbnick to do that), change the code to require it, and then switch to the new API, getting rid of the warning.

**Comment by spbnick** [comment]
Sure, go ahead, Shivam!

**Comment by shivam-Purohit** [comment]
Hey, where do I check for the changes I make? I still do not where to check for debugging purpose

**Comment by spbnick** [comment]
Can you register a Google Cloud account, and create a project for experiments? It's free for the first six months, but you would need a credit card.

**Comment by shivam-Purohit** [comment]
That will be required I guess. I tried a couple of methods but didn't work sadly. Also, I do not own a credit card.

**Comment by shivam-Purohit** [comment]
I have downloaded the gcp key and added the gcp credentials. What should I do next, should I create  a playground like specified in the submitter guide

**Comment by spbnick** [comment]
Just try deploying to your new project. Make sure you've exported the `GOOGLE_APPLICATION_CREDENTIALS` variable, pointing to your credentials file, then execute something like this `./cloud deploy kcidb-shivam "" 1 -v --smtp-mocked --test --heavy-asserts`.

**Comment by shivam-Purohit** [comment]
@spbnick is it deployed?
what should be my next course of action?
![ubuntu  Running  - Oracle VM VirtualBox 18-03-2023 13_08_31](https://user-images.githubusercontent.com/91889807/226092250-02f515f7-5dc8-47bf-a456-8aa16bfac941.png)

**Comment by spbnick** [comment]
Looks like it did deploy fine, indeed! Congrats :grinning: 

OK, now you need to reproduce the warning. IIRC, the warnings should pop up when you'd run some database tests. Try this, and see if you get the warning the issue is talking about:

```bash
./cloud env kcidb-shivam "" 1 --smtp-mocked --test --heavy-asserts -- \
    pytest --tb=native --verbosity=2 kcidb/test_db.py
```

This runs the database tests emulating the cloud environment, and using the clean/empty test databases in the deployment you made on your screenshot.

Write, if you don't get the warnings, and I'll try to find a way to reproduce them.

If you get them, read the Google Cloud docs regarding that warning and the interface in particular. Search the web and browse the BigQuery Python API docs for details.

I was able to find the issue deprecating the old interface: https://github.com/googleapis/google-cloud-python/issues/8989

It links to what seem to be a change updating the samples to the new interface: https://github.com/googleapis/python-bigquery/pull/309

And here's the documentation of the class we're supposed to be using instead: https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.dataset.Dataset

**Comment by spbnick** [comment]
> These command you specified does it need to be separated or together. I ran the command and it gave me this error

Ah, yep, I made a mistake in the command. Please replace `env` with `shell` there.

> If I run it separately all the tests passes.

The tests should pass in any case, but if you run them with deployed test databases, they will also run against BigQuery, and should produce the warnings.

**Comment by shivam-Purohit** [comment]
Got a tone of these including the big query one. I am happy the error occurred 😀


```
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:121
  /home/shivam/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: 14 warnings
  /home/shivam/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
  /home/shivam/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2349
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2349
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2349
../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2349
  /home/shivam/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2349: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(parent)

../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
  /home/shivam/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870
  /home/shivam/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.iam')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../.local/lib/python3.10/site-packages/google/rpc/__init__.py:20
  /home/shivam/.local/lib/python3.10/site-packages/google/rpc/__init__.py:20: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.rpc')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    pkg_resources.declare_namespace(__name__)

kcidb/db/bigquery/v04_00.py:73
kcidb/db/bigquery/v04_00.py:73
kcidb/db/bigquery/v04_00.py:73
kcidb/db/bigquery/v04_00.py:73
  /home/shivam/Desktop/pre-commit/kcidb/kcidb/db/bigquery/v04_00.py:73: PendingDeprecationWarning: Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
    self.dataset_ref = self.client.dataset(dataset_name)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by spbnick** [comment]
Awesome! Please ignore the "Deprecated call to `pkg_resources.declare_namespace('google.rpc')`", this is not our problem, it seems.

Good luck figuring out what to do with the warning. Don't hesitate to reach out here in the comments, or on Slack, with any questions you might have.

**Comment by spbnick** [comment]
Please post the output of `./cloud env kcidb-shivam "" 1 --smtp-mocked --test --heavy-asserts` on Slack (yes, `env` is correct this time) and I'll give you a faster command to run the tests reproducing the problem.

**Comment by shivam-Purohit** [comment]
I have shared the output. I will try figuring out things in the meantime.
