### ISSUE TITLE
Break down kcidb.orm module

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#386]
The [`kcidb.orm`](https://github.com/kernelci/kcidb/blob/main/kcidb/orm/__init__.py) module is now 1623 lines long, which is a bit much. 

We can extract parts of it into separate modules to make it more readable and maintainable.

Extract the `SCHEMA` variable and its dependencies and assertions into a new module called `kcidb.orm.data`.

Extract the `Pattern` class and its dependencies into a new module called `kcidb.orm.query`.

Update all references as necessary.

**Comment by octonawish-akcodes** [comment]
I want to take this.

**Comment by spbnick** [comment]
Sure! Have fun :smiley:
