### ISSUE TITLE
Support querying issues and incidents with kcidb(-db)-query

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#398]
At the moment, both the `kcidb-query` and its twin `kcidb-db-query` only support specifying the IDs for checkouts, builds, and tests to retrieve. However, the latest I/O and database schema versions have added support for incidents and issues. Add support for specifying IDs of those new objects to both tools, by adding support for two more option pairs: `-i`/`--issue-id` and `-n`/`--incident-id`. This involves modifying the `kcidb.db.QueryArgumentParser` class.

**Comment by spbnick** [comment]
Ha-ha, sure, don't hesitate to open PRs in general, but don't forget about the issues you already picked. If you don't want to finish an issue leave a comment there, so I can free it up. :+1:

**Comment by octonawish-akcodes** [comment]
Done
