### ISSUE TITLE
Verify if the latest test data has been sent to Grafana

### ISSUE THREAD

**Issue by crazoes** [kernelci/kcidb#544]
The latest releases from Gregkh for stable-rc 6.6, 6.1 and 6.9 are from 8th July.

![Image](https://github.com/kernelci/kcidb/assets/35893133/31640c4e-62b0-41b9-bdb9-9f76f3d2dee3)

When I was checking the data for the test results on Grafana dashboard to send out a report for this week, I realized that the last results were from 5th July.

![Image](https://github.com/kernelci/kcidb/assets/35893133/b405435d-6005-474b-a8b3-18ad9efcddc0)

One who works on sending out the data to Grafana dashboard needs to ensure that the results are up-to-date for all trees and branches ( I'm just using stable-rc to give example here but it's important to check other trees and branches as well)

**Comment by JenySadadia** [comment]
Hi,
I can see data for 6.1 and 6.6 on `playground` as well as `production` DB.
See the links:
- [playground](https://kcidb.kernelci.org/d/repository/repository?orgId=1&var-datasource=playground&var-origin=maestro&var-build_architecture=All&var-build_config_name=All&var-git_repository_url=https:%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fstable%2Flinux-stable-rc.git)
- [production](https://kcidb.kernelci.org/d/repository/repository?orgId=1&var-datasource=production&var-git_repository_url=https:%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fstable%2Flinux-stable-rc.git&var-origin=maestro&var-build_architecture=All&var-build_config_name=All)

**Comment by spbnick** [comment]
I can't see any relevant errors in the ingestion logs, FWIW. Doesn't mean they weren't lost somewhere, but makes it less likely.

**Comment by crazoes** [comment]
@JenySadadia @spbnick so probably there is some issue on the Grafana side?

cc @helen-fornazier

**Comment by spbnick** [comment]
@crazoes, not likely. Unless you can see the data in the old one, and not in the new one, or vice versa. We could also dig in the database a bit to make sure the data is not evading Grafana's queries somehow, but first I think it would be worth checking the Maestro logs, if @JenySadadia had time to implement them.

**Comment by JenySadadia** [comment]
As I mentioned earlier, I am able to see the submissions https://github.com/kernelci/kcidb/issues/544#issuecomment-2224658617.
Maybe there is something wrong with the new dashboard?

**Comment by spbnick** [comment]
So, did I get it right, that you can find what you're looking for on the old dashboard at kcidb.kernelci.org, but not on the new dashboard? If so, then it's up to @helen-fornazier to figure it out.

**Comment by crazoes** [comment]
@spbnick yes I think that is the case. We are just not able to see them on the new dashboard so I think this is something that @helen-fornazier needs to look into. I'll assign this to her.

**Comment by helen-fornazier** [comment]
![Image](https://github.com/user-attachments/assets/dbb87545-7f25-407d-b2e4-b6dc272fa84e)

we did have data submitted on 8th July, as well on 15th July, to both playground and production.

The tests you shown was filtering on paths with `kernelci_baseline`, which got recently renamed to `boot`. Please use `boot` or `%` to show all tests (but it takes a while to show).

@crazoes could you please confirm if you still don't see the data after these configuration?

**Comment by crazoes** [comment]
@helen-fornazier I can confirm that I'm able to see the data properly now but AFAIR, I didn't filter out things based on `kernelci_baseline` so not sure why I wasn't getting the results. I will keep this open for some more days to see if it doesn't happen in future.

**Comment by helen-fornazier** [comment]
`kernelci_baseline` was selected by default, I can see `kernelci_baseline` written in the screen you shared

**Comment by crazoes** [comment]
This has been resolved now. It was due to incorrect default values set in grafana which has been fixed by Helen now.
