### ISSUE TITLE
Consider supporting validating against a specific version with kcidb-validate

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#78]

**Comment by spbnick** [comment]
The `kcidb-validate` command available after installing KCIDB will validate I/O data against any of the supported schema versions. Like this:

```console
$ kcidb-validate <<<'{"version": {"major": 4}}'
$ kcidb-validate <<<'{"version": {"major": 3}}'
$ kcidb-validate <<<'{"version": {"major": 2}}'
$ kcidb-validate <<<'{"version": {"major": 1}}'
```

Make the `kcidb-validate` tool accept a single positional argument specifying the exact version of the schema to validate against, so that this command works:

```
$ kcidb-validate 4 <<<'{"version": {"major": 4}}'
```

But this command fails validation:

```
$ kcidb-validate 3 <<<'{"version": {"major": 4}}'
```

**Comment by pawiecz** [comment]
The implementation is ready; I still have to adjust doc strings and tests
